### ISSUE TITLE
"Cannot find BLT alias to install."

### ISSUE THREAD

**Issue by carsten-propeople** [acquia/blt-vm#13]
After update to blt 13.0.0 I get the following error with vagrant provision:

"Cannot find BLT alias to install.", "stdout_lines": ["Cannot find BLT alias to install."]} on
acquia/blt-drupal-vm/scripts/drupal-vm/post-provision.php script.

Probably due to https://github.com/acquia/blt/pull/4364

**Comment by UTCGilligan** [comment]
Possibly the Drupal-vm plugin needs to have the BLT alias made available via the BLT Launcher .phar or added to the $PATH as described in "Alternatives" in the [BLT Launcher README](https://github.com/acquia/blt-launcher).

**Comment by gauravmanerkar** [comment]
Hello,

I am facing same issue after upgrading to v13.
Post provision script will need to be updated in Blt-vm.

**Comment by DimitrisKaskarelis** [comment]
It looks like the `post-provision.php` script is indeed looking for `/vagrant/vendor/acquia/blt/scripts/blt/alias` which no longer exists as of acquia/blt#4364 .

Instead we could just replace `post-provision.php` with `post-provision.sh` to include the setup on https://github.com/acquia/blt-launcher and modify `config.yml` post provision script  section

```
post_provision_scripts:
  - "../../../acquia/blt-drupal-vm/scripts/drupal-vm/configure-solr.sh"
  - "../../../acquia/blt-drupal-vm/scripts/drupal-vm/post-provision.php" <----
```


Will be taking a closer look soon

**Comment by gauravmanerkar** [comment]
@DimitrisKaskarelis 
There is no `post-provision.sh` file

https://github.com/acquia/blt-vm/tree/master/scripts/drupal-vm

**Comment by DimitrisKaskarelis** [comment]
@manerkargaurav you are right there is no `post-provision.sh`. In my above comment I was proposing the general outline of a solution which would require creating a `post-provision.sh` to replace `post-provision.php`.

**Comment by dkaskarelis** [comment]
@manerkargaurav would you be able to test the code from the  PR  #14 ?

**Comment by JeeMo** [comment]
@dkaskarelis I know I am not @manerkargaurav but I did roll a patch from your PR and tested it on my local project and it did fix the issue for me with drupal/core-recommended: 9.3.x-dev and acquia/blt: 12.8.2

Thanks, it was a huge help!

**Comment by DimitrisKaskarelis** [comment]
Thank  you very much @JeeMo ! Could you post a comment on the PR #14 noting that the patch has been tested by you so that we can move towards a merge ?

**Comment by JeeMo** [comment]
Comment posted.

Thanks for the patch!

Jee
